### ISSUE TITLE
Export declared interfaces

### ISSUE THREAD

**Issue by eddiesholl** [smelukov/estel-estree-builder#1]
Hey there,

Just wondering if you would consider a PR to make the generated interfaces in the ts output to be exported.

**Comment by smelukov** [comment]
Hi! Thanks for the issue.
It's fixed in https://github.com/smelukov/estel-estree-builder/commit/82c7ff54d59bad61b80f8909308bfb67c7a0d5d9
Please update to 0.2.0

**Comment by eddiesholl** [comment]
Awesome! I think you need to run the publish to npm

**Comment by smelukov** [comment]
Already ;)
