### ISSUE TITLE
Node types aren't typechecked

### ISSUE THREAD

**Issue by glmdgrielson** [smelukov/estel-estree-builder#3]
I noticed that the generated interfaces you have don't properly set the `type` field. The DefinitelyTyped repo goes out of its way to do let the user make runtime checks on such things, but here every single node has its `type` listed as string. Is this intentional?

**Comment by smelukov** [comment]
Yes. `type` is a field of every AST-node. You can see it [here](https://github.com/estree/estree/blob/master/es5.md#node-objects).
This is not a type of data (like `type` keyword in TS), this is a type of AST-node.
[Here](https://astexplorer.net/#/gist/e3afb60a1262da45c279f230fa6e6f7d/973e887dd73972b3516da78291045893a1d306dd) see that every AST-node has this field.
